#!/usr/bin/env bash
# Configures Nginx with a custom HTTP header X-Served-By
apt-get update -y
apt-get install nginx -y
# Add the header specifically inside the server block
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By \$HOSTNAME;/" /etc/nginx/sites-available/default
service nginx restart
