#!/usr/bin/env bash
# Installs and configures HAProxy for round-robin load balancing
apt-get update -y
apt-get install haproxy -y
cat << 'EOC' >> /etc/haproxy/haproxy.cfg
frontend alu_lb
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 <web-01_IP>:80 check
    server web-02 <web-02_IP>:80 check
EOC
service haproxy restart
