#!/usr/bin/env bash
# Fixes Nginx to listen on port 80 by removing port 8080 configs
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default
# Force a restart to apply changes
service nginx restart
