#!/usr/bin/env bash
# Configures Nginx with a 301 redirection
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a \    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/ssh/ssh_config /etc/nginx/sites-available/default
service nginx restart
