#!/usr/bin/env bash
# Configures Nginx with a custom 404 page
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a \    error_page 404 /404.html;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx restart
